// Generated by ProtoGen, Version=2.4.1.473, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace bgs.protocol.channel.v2 {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public static partial class ChannelEnum {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static ChannelEnum() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          "CjJiZ3MvbG93L3BiL2NsaWVudC9hcGkvY2xpZW50L3YyL2NoYW5uZWxfZW51" + 
          "bS5wcm90bxIXYmdzLnByb3RvY29sLmNoYW5uZWwudjIqYwoMUHJpdmFjeUxl" + 
          "dmVsEhYKElBSSVZBQ1lfTEVWRUxfT1BFThABEiEKHVBSSVZBQ1lfTEVWRUxf" + 
          "T1BFTl9JTlZJVEFUSU9OEAMSGAoUUFJJVkFDWV9MRVZFTF9DTE9TRUQQBCqB" + 
          "AwoUQ2hhbm5lbFJlbW92ZWRSZWFzb24SJgoiQ0hBTk5FTF9SRU1PVkVEX1JF" + 
          "QVNPTl9NRU1CRVJfTEVGVBAAEigKJENIQU5ORUxfUkVNT1ZFRF9SRUFTT05f" + 
          "TUVNQkVSX0tJQ0tFRBABEi4KKkNIQU5ORUxfUkVNT1ZFRF9SRUFTT05fRElT" + 
          "U09MVkVEX0JZX01FTUJFUhACEi4KKkNIQU5ORUxfUkVNT1ZFRF9SRUFTT05f" + 
          "TUVNQkVSX0RJU0NPTk5FQ1RFRBADEjQKMENIQU5ORUxfUkVNT1ZFRF9SRUFT" + 
          "T05fTUVNQkVSX1JFTU9WRURfQllfU0VSVklDRRAEEi8KK0NIQU5ORUxfUkVN" + 
          "T1ZFRF9SRUFTT05fRElTU09MVkVEX0JZX1NFUlZJQ0UQBRInCiNDSEFOTkVM" + 
          "X1JFTU9WRURfUkVBU09OX0RJU0NPTk5FQ1RFRBAGEicKI0NIQU5ORUxfUkVN" + 
          "T1ZFRF9SRUFTT05fRk9VTkRFUl9MRUZUEA4=");
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
  #region Enums
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public enum PrivacyLevel {
    PRIVACY_LEVEL_OPEN = 1,
    PRIVACY_LEVEL_OPEN_INVITATION = 3,
    PRIVACY_LEVEL_CLOSED = 4,
  }
  
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public enum ChannelRemovedReason {
    CHANNEL_REMOVED_REASON_MEMBER_LEFT = 0,
    CHANNEL_REMOVED_REASON_MEMBER_KICKED = 1,
    CHANNEL_REMOVED_REASON_DISSOLVED_BY_MEMBER = 2,
    CHANNEL_REMOVED_REASON_MEMBER_DISCONNECTED = 3,
    CHANNEL_REMOVED_REASON_MEMBER_REMOVED_BY_SERVICE = 4,
    CHANNEL_REMOVED_REASON_DISSOLVED_BY_SERVICE = 5,
    CHANNEL_REMOVED_REASON_DISCONNECTED = 6,
    CHANNEL_REMOVED_REASON_FOUNDER_LEFT = 14,
  }
  
  #endregion
  
}

#endregion Designer generated code
