// Generated by ProtoGen, Version=2.4.1.473, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace bgs.protocol.channel {
  
  namespace Proto {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public static partial class ChannelRoleSet {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_bgs_protocol_channel_ChannelPrivilegeSet__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.channel.ChannelPrivilegeSet, global::bgs.protocol.channel.ChannelPrivilegeSet.Builder> internal__static_bgs_protocol_channel_ChannelPrivilegeSet__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_bgs_protocol_channel_ChannelRole__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.channel.ChannelRole, global::bgs.protocol.channel.ChannelRole.Builder> internal__static_bgs_protocol_channel_ChannelRole__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_bgs_protocol_channel_ChannelRoleSet__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.channel.ChannelRoleSet, global::bgs.protocol.channel.ChannelRoleSet.Builder> internal__static_bgs_protocol_channel_ChannelRoleSet__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;
      
      static ChannelRoleSet() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            "CihiZ3MvbG93L3BiL2NsaWVudC9jaGFubmVsX3JvbGVfc2V0LnByb3RvEhRi" + 
            "Z3MucHJvdG9jb2wuY2hhbm5lbBoiYmdzL2xvdy9wYi9jbGllbnQvcm9sZV90" + 
            "eXBlcy5wcm90byLFBQoTQ2hhbm5lbFByaXZpbGVnZVNldBIdCgpjYW5faW52" + 
            "aXRlGAEgASgIUgljYW5JbnZpdGUSPQobY2FuX2ludml0ZV93aXRoX3Jlc2Vy" + 
            "dmF0aW9uGAIgASgIUhhjYW5JbnZpdGVXaXRoUmVzZXJ2YXRpb24SPQobY2Fu" + 
            "X3Jldm9rZV9vdGhlcl9pbnZpdGF0aW9uGAMgASgIUhhjYW5SZXZva2VPdGhl" + 
            "ckludml0YXRpb24SOQoZY2FuX3Jldm9rZV9vd25faW52aXRhdGlvbhgEIAEo" + 
            "CFIWY2FuUmV2b2tlT3duSW52aXRhdGlvbhIZCghjYW5fa2ljaxgFIAEoCFIH" + 
            "Y2FuS2ljaxIhCgxjYW5fZGlzc29sdmUYBiABKAhSC2NhbkRpc3NvbHZlEiYK" + 
            "D2Nhbl9zZXRfcHJpdmFjeRgHIAEoCFINY2FuU2V0UHJpdmFjeRIoChBjYW5f" + 
            "c2VuZF9tZXNzYWdlGAggASgIUg5jYW5TZW5kTWVzc2FnZRIuChNjYW5fcmVj" + 
            "ZWl2ZV9tZXNzYWdlGAkgASgIUhFjYW5SZWNlaXZlTWVzc2FnZRIqChFjYW5f" + 
            "c2V0X2F0dHJpYnV0ZRgKIAEoCFIPY2FuU2V0QXR0cmlidXRlEkIKHmNhbl9z" + 
            "ZXRfb3RoZXJfbWVtYmVyX2F0dHJpYnV0ZRgLIAEoCFIaY2FuU2V0T3RoZXJN" + 
            "ZW1iZXJBdHRyaWJ1dGUSPgocY2FuX3NldF9vd25fbWVtYmVyX2F0dHJpYnV0" + 
            "ZRgMIAEoCFIYY2FuU2V0T3duTWVtYmVyQXR0cmlidXRlEiQKDmNhbl9lbnRl" + 
            "cl9nYW1lGA0gASgIUgxjYW5FbnRlckdhbWUSHwoLY2FuX3N1Z2dlc3QYDiAB" + 
            "KAhSCmNhblN1Z2dlc3QSHwoLY2FuX2FwcHJvdmUYDyABKAhSCmNhbkFwcHJv" + 
            "dmUilQEKC0NoYW5uZWxSb2xlEg4KAmlkGAEgASgNUgJpZBItCgVzdGF0ZRgC" + 
            "IAEoCzIXLmJncy5wcm90b2NvbC5Sb2xlU3RhdGVSBXN0YXRlEkcKCXByaXZp" + 
            "bGVnZRgDIAEoCzIpLmJncy5wcm90b2NvbC5jaGFubmVsLkNoYW5uZWxQcml2" + 
            "aWxlZ2VTZXRSCXByaXZpbGVnZSKCAQoOQ2hhbm5lbFJvbGVTZXQSNQoEcm9s" + 
            "ZRgBIAMoCzIhLmJncy5wcm90b2NvbC5jaGFubmVsLkNoYW5uZWxSb2xlUgRy" + 
            "b2xlEiUKDGRlZmF1bHRfcm9sZRgCIAMoDUICEAFSC2RlZmF1bHRSb2xlEhIK" + 
            "BG5hbWUYAyABKAlSBG5hbWU=");
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_bgs_protocol_channel_ChannelPrivilegeSet__Descriptor = Descriptor.MessageTypes[0];
          internal__static_bgs_protocol_channel_ChannelPrivilegeSet__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.channel.ChannelPrivilegeSet, global::bgs.protocol.channel.ChannelPrivilegeSet.Builder>(internal__static_bgs_protocol_channel_ChannelPrivilegeSet__Descriptor,
                  new string[] { "CanInvite", "CanInviteWithReservation", "CanRevokeOtherInvitation", "CanRevokeOwnInvitation", "CanKick", "CanDissolve", "CanSetPrivacy", "CanSendMessage", "CanReceiveMessage", "CanSetAttribute", "CanSetOtherMemberAttribute", "CanSetOwnMemberAttribute", "CanEnterGame", "CanSuggest", "CanApprove", });
          internal__static_bgs_protocol_channel_ChannelRole__Descriptor = Descriptor.MessageTypes[1];
          internal__static_bgs_protocol_channel_ChannelRole__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.channel.ChannelRole, global::bgs.protocol.channel.ChannelRole.Builder>(internal__static_bgs_protocol_channel_ChannelRole__Descriptor,
                  new string[] { "Id", "State", "Privilege", });
          internal__static_bgs_protocol_channel_ChannelRoleSet__Descriptor = Descriptor.MessageTypes[2];
          internal__static_bgs_protocol_channel_ChannelRoleSet__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.channel.ChannelRoleSet, global::bgs.protocol.channel.ChannelRoleSet.Builder>(internal__static_bgs_protocol_channel_ChannelRoleSet__Descriptor,
                  new string[] { "Role", "DefaultRole", "Name", });
          pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
          RegisterAllExtensions(registry);
          global::bgs.protocol.RoleTypes.RegisterAllExtensions(registry);
          return registry;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            global::bgs.protocol.RoleTypes.Descriptor, 
            }, assigner);
      }
      #endregion
      
    }
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class ChannelPrivilegeSet : pb::GeneratedMessage<ChannelPrivilegeSet, ChannelPrivilegeSet.Builder> {
    private ChannelPrivilegeSet() { }
    private static readonly ChannelPrivilegeSet defaultInstance = new ChannelPrivilegeSet().MakeReadOnly();
    private static readonly string[] _channelPrivilegeSetFieldNames = new string[] { "can_approve", "can_dissolve", "can_enter_game", "can_invite", "can_invite_with_reservation", "can_kick", "can_receive_message", "can_revoke_other_invitation", "can_revoke_own_invitation", "can_send_message", "can_set_attribute", "can_set_other_member_attribute", "can_set_own_member_attribute", "can_set_privacy", "can_suggest" };
    private static readonly uint[] _channelPrivilegeSetFieldTags = new uint[] { 120, 48, 104, 8, 16, 40, 72, 24, 32, 64, 80, 88, 96, 56, 112 };
    public static ChannelPrivilegeSet DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override ChannelPrivilegeSet DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override ChannelPrivilegeSet ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::bgs.protocol.channel.Proto.ChannelRoleSet.internal__static_bgs_protocol_channel_ChannelPrivilegeSet__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<ChannelPrivilegeSet, ChannelPrivilegeSet.Builder> InternalFieldAccessors {
      get { return global::bgs.protocol.channel.Proto.ChannelRoleSet.internal__static_bgs_protocol_channel_ChannelPrivilegeSet__FieldAccessorTable; }
    }
    
    public const int CanInviteFieldNumber = 1;
    private bool hasCanInvite;
    private bool canInvite_;
    public bool HasCanInvite {
      get { return hasCanInvite; }
    }
    public bool CanInvite {
      get { return canInvite_; }
    }
    
    public const int CanInviteWithReservationFieldNumber = 2;
    private bool hasCanInviteWithReservation;
    private bool canInviteWithReservation_;
    public bool HasCanInviteWithReservation {
      get { return hasCanInviteWithReservation; }
    }
    public bool CanInviteWithReservation {
      get { return canInviteWithReservation_; }
    }
    
    public const int CanRevokeOtherInvitationFieldNumber = 3;
    private bool hasCanRevokeOtherInvitation;
    private bool canRevokeOtherInvitation_;
    public bool HasCanRevokeOtherInvitation {
      get { return hasCanRevokeOtherInvitation; }
    }
    public bool CanRevokeOtherInvitation {
      get { return canRevokeOtherInvitation_; }
    }
    
    public const int CanRevokeOwnInvitationFieldNumber = 4;
    private bool hasCanRevokeOwnInvitation;
    private bool canRevokeOwnInvitation_;
    public bool HasCanRevokeOwnInvitation {
      get { return hasCanRevokeOwnInvitation; }
    }
    public bool CanRevokeOwnInvitation {
      get { return canRevokeOwnInvitation_; }
    }
    
    public const int CanKickFieldNumber = 5;
    private bool hasCanKick;
    private bool canKick_;
    public bool HasCanKick {
      get { return hasCanKick; }
    }
    public bool CanKick {
      get { return canKick_; }
    }
    
    public const int CanDissolveFieldNumber = 6;
    private bool hasCanDissolve;
    private bool canDissolve_;
    public bool HasCanDissolve {
      get { return hasCanDissolve; }
    }
    public bool CanDissolve {
      get { return canDissolve_; }
    }
    
    public const int CanSetPrivacyFieldNumber = 7;
    private bool hasCanSetPrivacy;
    private bool canSetPrivacy_;
    public bool HasCanSetPrivacy {
      get { return hasCanSetPrivacy; }
    }
    public bool CanSetPrivacy {
      get { return canSetPrivacy_; }
    }
    
    public const int CanSendMessageFieldNumber = 8;
    private bool hasCanSendMessage;
    private bool canSendMessage_;
    public bool HasCanSendMessage {
      get { return hasCanSendMessage; }
    }
    public bool CanSendMessage {
      get { return canSendMessage_; }
    }
    
    public const int CanReceiveMessageFieldNumber = 9;
    private bool hasCanReceiveMessage;
    private bool canReceiveMessage_;
    public bool HasCanReceiveMessage {
      get { return hasCanReceiveMessage; }
    }
    public bool CanReceiveMessage {
      get { return canReceiveMessage_; }
    }
    
    public const int CanSetAttributeFieldNumber = 10;
    private bool hasCanSetAttribute;
    private bool canSetAttribute_;
    public bool HasCanSetAttribute {
      get { return hasCanSetAttribute; }
    }
    public bool CanSetAttribute {
      get { return canSetAttribute_; }
    }
    
    public const int CanSetOtherMemberAttributeFieldNumber = 11;
    private bool hasCanSetOtherMemberAttribute;
    private bool canSetOtherMemberAttribute_;
    public bool HasCanSetOtherMemberAttribute {
      get { return hasCanSetOtherMemberAttribute; }
    }
    public bool CanSetOtherMemberAttribute {
      get { return canSetOtherMemberAttribute_; }
    }
    
    public const int CanSetOwnMemberAttributeFieldNumber = 12;
    private bool hasCanSetOwnMemberAttribute;
    private bool canSetOwnMemberAttribute_;
    public bool HasCanSetOwnMemberAttribute {
      get { return hasCanSetOwnMemberAttribute; }
    }
    public bool CanSetOwnMemberAttribute {
      get { return canSetOwnMemberAttribute_; }
    }
    
    public const int CanEnterGameFieldNumber = 13;
    private bool hasCanEnterGame;
    private bool canEnterGame_;
    public bool HasCanEnterGame {
      get { return hasCanEnterGame; }
    }
    public bool CanEnterGame {
      get { return canEnterGame_; }
    }
    
    public const int CanSuggestFieldNumber = 14;
    private bool hasCanSuggest;
    private bool canSuggest_;
    public bool HasCanSuggest {
      get { return hasCanSuggest; }
    }
    public bool CanSuggest {
      get { return canSuggest_; }
    }
    
    public const int CanApproveFieldNumber = 15;
    private bool hasCanApprove;
    private bool canApprove_;
    public bool HasCanApprove {
      get { return hasCanApprove; }
    }
    public bool CanApprove {
      get { return canApprove_; }
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _channelPrivilegeSetFieldNames;
      if (hasCanInvite) {
        output.WriteBool(1, field_names[3], CanInvite);
      }
      if (hasCanInviteWithReservation) {
        output.WriteBool(2, field_names[4], CanInviteWithReservation);
      }
      if (hasCanRevokeOtherInvitation) {
        output.WriteBool(3, field_names[7], CanRevokeOtherInvitation);
      }
      if (hasCanRevokeOwnInvitation) {
        output.WriteBool(4, field_names[8], CanRevokeOwnInvitation);
      }
      if (hasCanKick) {
        output.WriteBool(5, field_names[5], CanKick);
      }
      if (hasCanDissolve) {
        output.WriteBool(6, field_names[1], CanDissolve);
      }
      if (hasCanSetPrivacy) {
        output.WriteBool(7, field_names[13], CanSetPrivacy);
      }
      if (hasCanSendMessage) {
        output.WriteBool(8, field_names[9], CanSendMessage);
      }
      if (hasCanReceiveMessage) {
        output.WriteBool(9, field_names[6], CanReceiveMessage);
      }
      if (hasCanSetAttribute) {
        output.WriteBool(10, field_names[10], CanSetAttribute);
      }
      if (hasCanSetOtherMemberAttribute) {
        output.WriteBool(11, field_names[11], CanSetOtherMemberAttribute);
      }
      if (hasCanSetOwnMemberAttribute) {
        output.WriteBool(12, field_names[12], CanSetOwnMemberAttribute);
      }
      if (hasCanEnterGame) {
        output.WriteBool(13, field_names[2], CanEnterGame);
      }
      if (hasCanSuggest) {
        output.WriteBool(14, field_names[14], CanSuggest);
      }
      if (hasCanApprove) {
        output.WriteBool(15, field_names[0], CanApprove);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasCanInvite) {
          size += pb::CodedOutputStream.ComputeBoolSize(1, CanInvite);
        }
        if (hasCanInviteWithReservation) {
          size += pb::CodedOutputStream.ComputeBoolSize(2, CanInviteWithReservation);
        }
        if (hasCanRevokeOtherInvitation) {
          size += pb::CodedOutputStream.ComputeBoolSize(3, CanRevokeOtherInvitation);
        }
        if (hasCanRevokeOwnInvitation) {
          size += pb::CodedOutputStream.ComputeBoolSize(4, CanRevokeOwnInvitation);
        }
        if (hasCanKick) {
          size += pb::CodedOutputStream.ComputeBoolSize(5, CanKick);
        }
        if (hasCanDissolve) {
          size += pb::CodedOutputStream.ComputeBoolSize(6, CanDissolve);
        }
        if (hasCanSetPrivacy) {
          size += pb::CodedOutputStream.ComputeBoolSize(7, CanSetPrivacy);
        }
        if (hasCanSendMessage) {
          size += pb::CodedOutputStream.ComputeBoolSize(8, CanSendMessage);
        }
        if (hasCanReceiveMessage) {
          size += pb::CodedOutputStream.ComputeBoolSize(9, CanReceiveMessage);
        }
        if (hasCanSetAttribute) {
          size += pb::CodedOutputStream.ComputeBoolSize(10, CanSetAttribute);
        }
        if (hasCanSetOtherMemberAttribute) {
          size += pb::CodedOutputStream.ComputeBoolSize(11, CanSetOtherMemberAttribute);
        }
        if (hasCanSetOwnMemberAttribute) {
          size += pb::CodedOutputStream.ComputeBoolSize(12, CanSetOwnMemberAttribute);
        }
        if (hasCanEnterGame) {
          size += pb::CodedOutputStream.ComputeBoolSize(13, CanEnterGame);
        }
        if (hasCanSuggest) {
          size += pb::CodedOutputStream.ComputeBoolSize(14, CanSuggest);
        }
        if (hasCanApprove) {
          size += pb::CodedOutputStream.ComputeBoolSize(15, CanApprove);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static ChannelPrivilegeSet ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ChannelPrivilegeSet ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ChannelPrivilegeSet ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ChannelPrivilegeSet ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ChannelPrivilegeSet ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ChannelPrivilegeSet ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static ChannelPrivilegeSet ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static ChannelPrivilegeSet ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static ChannelPrivilegeSet ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ChannelPrivilegeSet ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private ChannelPrivilegeSet MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(ChannelPrivilegeSet prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<ChannelPrivilegeSet, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(ChannelPrivilegeSet cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private ChannelPrivilegeSet result;
      
      private ChannelPrivilegeSet PrepareBuilder() {
        if (resultIsReadOnly) {
          ChannelPrivilegeSet original = result;
          result = new ChannelPrivilegeSet();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override ChannelPrivilegeSet MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::bgs.protocol.channel.ChannelPrivilegeSet.Descriptor; }
      }
      
      public override ChannelPrivilegeSet DefaultInstanceForType {
        get { return global::bgs.protocol.channel.ChannelPrivilegeSet.DefaultInstance; }
      }
      
      public override ChannelPrivilegeSet BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is ChannelPrivilegeSet) {
          return MergeFrom((ChannelPrivilegeSet) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(ChannelPrivilegeSet other) {
        if (other == global::bgs.protocol.channel.ChannelPrivilegeSet.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasCanInvite) {
          CanInvite = other.CanInvite;
        }
        if (other.HasCanInviteWithReservation) {
          CanInviteWithReservation = other.CanInviteWithReservation;
        }
        if (other.HasCanRevokeOtherInvitation) {
          CanRevokeOtherInvitation = other.CanRevokeOtherInvitation;
        }
        if (other.HasCanRevokeOwnInvitation) {
          CanRevokeOwnInvitation = other.CanRevokeOwnInvitation;
        }
        if (other.HasCanKick) {
          CanKick = other.CanKick;
        }
        if (other.HasCanDissolve) {
          CanDissolve = other.CanDissolve;
        }
        if (other.HasCanSetPrivacy) {
          CanSetPrivacy = other.CanSetPrivacy;
        }
        if (other.HasCanSendMessage) {
          CanSendMessage = other.CanSendMessage;
        }
        if (other.HasCanReceiveMessage) {
          CanReceiveMessage = other.CanReceiveMessage;
        }
        if (other.HasCanSetAttribute) {
          CanSetAttribute = other.CanSetAttribute;
        }
        if (other.HasCanSetOtherMemberAttribute) {
          CanSetOtherMemberAttribute = other.CanSetOtherMemberAttribute;
        }
        if (other.HasCanSetOwnMemberAttribute) {
          CanSetOwnMemberAttribute = other.CanSetOwnMemberAttribute;
        }
        if (other.HasCanEnterGame) {
          CanEnterGame = other.CanEnterGame;
        }
        if (other.HasCanSuggest) {
          CanSuggest = other.CanSuggest;
        }
        if (other.HasCanApprove) {
          CanApprove = other.CanApprove;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_channelPrivilegeSetFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _channelPrivilegeSetFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              result.hasCanInvite = input.ReadBool(ref result.canInvite_);
              break;
            }
            case 16: {
              result.hasCanInviteWithReservation = input.ReadBool(ref result.canInviteWithReservation_);
              break;
            }
            case 24: {
              result.hasCanRevokeOtherInvitation = input.ReadBool(ref result.canRevokeOtherInvitation_);
              break;
            }
            case 32: {
              result.hasCanRevokeOwnInvitation = input.ReadBool(ref result.canRevokeOwnInvitation_);
              break;
            }
            case 40: {
              result.hasCanKick = input.ReadBool(ref result.canKick_);
              break;
            }
            case 48: {
              result.hasCanDissolve = input.ReadBool(ref result.canDissolve_);
              break;
            }
            case 56: {
              result.hasCanSetPrivacy = input.ReadBool(ref result.canSetPrivacy_);
              break;
            }
            case 64: {
              result.hasCanSendMessage = input.ReadBool(ref result.canSendMessage_);
              break;
            }
            case 72: {
              result.hasCanReceiveMessage = input.ReadBool(ref result.canReceiveMessage_);
              break;
            }
            case 80: {
              result.hasCanSetAttribute = input.ReadBool(ref result.canSetAttribute_);
              break;
            }
            case 88: {
              result.hasCanSetOtherMemberAttribute = input.ReadBool(ref result.canSetOtherMemberAttribute_);
              break;
            }
            case 96: {
              result.hasCanSetOwnMemberAttribute = input.ReadBool(ref result.canSetOwnMemberAttribute_);
              break;
            }
            case 104: {
              result.hasCanEnterGame = input.ReadBool(ref result.canEnterGame_);
              break;
            }
            case 112: {
              result.hasCanSuggest = input.ReadBool(ref result.canSuggest_);
              break;
            }
            case 120: {
              result.hasCanApprove = input.ReadBool(ref result.canApprove_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasCanInvite {
        get { return result.hasCanInvite; }
      }
      public bool CanInvite {
        get { return result.CanInvite; }
        set { SetCanInvite(value); }
      }
      public Builder SetCanInvite(bool value) {
        PrepareBuilder();
        result.hasCanInvite = true;
        result.canInvite_ = value;
        return this;
      }
      public Builder ClearCanInvite() {
        PrepareBuilder();
        result.hasCanInvite = false;
        result.canInvite_ = false;
        return this;
      }
      
      public bool HasCanInviteWithReservation {
        get { return result.hasCanInviteWithReservation; }
      }
      public bool CanInviteWithReservation {
        get { return result.CanInviteWithReservation; }
        set { SetCanInviteWithReservation(value); }
      }
      public Builder SetCanInviteWithReservation(bool value) {
        PrepareBuilder();
        result.hasCanInviteWithReservation = true;
        result.canInviteWithReservation_ = value;
        return this;
      }
      public Builder ClearCanInviteWithReservation() {
        PrepareBuilder();
        result.hasCanInviteWithReservation = false;
        result.canInviteWithReservation_ = false;
        return this;
      }
      
      public bool HasCanRevokeOtherInvitation {
        get { return result.hasCanRevokeOtherInvitation; }
      }
      public bool CanRevokeOtherInvitation {
        get { return result.CanRevokeOtherInvitation; }
        set { SetCanRevokeOtherInvitation(value); }
      }
      public Builder SetCanRevokeOtherInvitation(bool value) {
        PrepareBuilder();
        result.hasCanRevokeOtherInvitation = true;
        result.canRevokeOtherInvitation_ = value;
        return this;
      }
      public Builder ClearCanRevokeOtherInvitation() {
        PrepareBuilder();
        result.hasCanRevokeOtherInvitation = false;
        result.canRevokeOtherInvitation_ = false;
        return this;
      }
      
      public bool HasCanRevokeOwnInvitation {
        get { return result.hasCanRevokeOwnInvitation; }
      }
      public bool CanRevokeOwnInvitation {
        get { return result.CanRevokeOwnInvitation; }
        set { SetCanRevokeOwnInvitation(value); }
      }
      public Builder SetCanRevokeOwnInvitation(bool value) {
        PrepareBuilder();
        result.hasCanRevokeOwnInvitation = true;
        result.canRevokeOwnInvitation_ = value;
        return this;
      }
      public Builder ClearCanRevokeOwnInvitation() {
        PrepareBuilder();
        result.hasCanRevokeOwnInvitation = false;
        result.canRevokeOwnInvitation_ = false;
        return this;
      }
      
      public bool HasCanKick {
        get { return result.hasCanKick; }
      }
      public bool CanKick {
        get { return result.CanKick; }
        set { SetCanKick(value); }
      }
      public Builder SetCanKick(bool value) {
        PrepareBuilder();
        result.hasCanKick = true;
        result.canKick_ = value;
        return this;
      }
      public Builder ClearCanKick() {
        PrepareBuilder();
        result.hasCanKick = false;
        result.canKick_ = false;
        return this;
      }
      
      public bool HasCanDissolve {
        get { return result.hasCanDissolve; }
      }
      public bool CanDissolve {
        get { return result.CanDissolve; }
        set { SetCanDissolve(value); }
      }
      public Builder SetCanDissolve(bool value) {
        PrepareBuilder();
        result.hasCanDissolve = true;
        result.canDissolve_ = value;
        return this;
      }
      public Builder ClearCanDissolve() {
        PrepareBuilder();
        result.hasCanDissolve = false;
        result.canDissolve_ = false;
        return this;
      }
      
      public bool HasCanSetPrivacy {
        get { return result.hasCanSetPrivacy; }
      }
      public bool CanSetPrivacy {
        get { return result.CanSetPrivacy; }
        set { SetCanSetPrivacy(value); }
      }
      public Builder SetCanSetPrivacy(bool value) {
        PrepareBuilder();
        result.hasCanSetPrivacy = true;
        result.canSetPrivacy_ = value;
        return this;
      }
      public Builder ClearCanSetPrivacy() {
        PrepareBuilder();
        result.hasCanSetPrivacy = false;
        result.canSetPrivacy_ = false;
        return this;
      }
      
      public bool HasCanSendMessage {
        get { return result.hasCanSendMessage; }
      }
      public bool CanSendMessage {
        get { return result.CanSendMessage; }
        set { SetCanSendMessage(value); }
      }
      public Builder SetCanSendMessage(bool value) {
        PrepareBuilder();
        result.hasCanSendMessage = true;
        result.canSendMessage_ = value;
        return this;
      }
      public Builder ClearCanSendMessage() {
        PrepareBuilder();
        result.hasCanSendMessage = false;
        result.canSendMessage_ = false;
        return this;
      }
      
      public bool HasCanReceiveMessage {
        get { return result.hasCanReceiveMessage; }
      }
      public bool CanReceiveMessage {
        get { return result.CanReceiveMessage; }
        set { SetCanReceiveMessage(value); }
      }
      public Builder SetCanReceiveMessage(bool value) {
        PrepareBuilder();
        result.hasCanReceiveMessage = true;
        result.canReceiveMessage_ = value;
        return this;
      }
      public Builder ClearCanReceiveMessage() {
        PrepareBuilder();
        result.hasCanReceiveMessage = false;
        result.canReceiveMessage_ = false;
        return this;
      }
      
      public bool HasCanSetAttribute {
        get { return result.hasCanSetAttribute; }
      }
      public bool CanSetAttribute {
        get { return result.CanSetAttribute; }
        set { SetCanSetAttribute(value); }
      }
      public Builder SetCanSetAttribute(bool value) {
        PrepareBuilder();
        result.hasCanSetAttribute = true;
        result.canSetAttribute_ = value;
        return this;
      }
      public Builder ClearCanSetAttribute() {
        PrepareBuilder();
        result.hasCanSetAttribute = false;
        result.canSetAttribute_ = false;
        return this;
      }
      
      public bool HasCanSetOtherMemberAttribute {
        get { return result.hasCanSetOtherMemberAttribute; }
      }
      public bool CanSetOtherMemberAttribute {
        get { return result.CanSetOtherMemberAttribute; }
        set { SetCanSetOtherMemberAttribute(value); }
      }
      public Builder SetCanSetOtherMemberAttribute(bool value) {
        PrepareBuilder();
        result.hasCanSetOtherMemberAttribute = true;
        result.canSetOtherMemberAttribute_ = value;
        return this;
      }
      public Builder ClearCanSetOtherMemberAttribute() {
        PrepareBuilder();
        result.hasCanSetOtherMemberAttribute = false;
        result.canSetOtherMemberAttribute_ = false;
        return this;
      }
      
      public bool HasCanSetOwnMemberAttribute {
        get { return result.hasCanSetOwnMemberAttribute; }
      }
      public bool CanSetOwnMemberAttribute {
        get { return result.CanSetOwnMemberAttribute; }
        set { SetCanSetOwnMemberAttribute(value); }
      }
      public Builder SetCanSetOwnMemberAttribute(bool value) {
        PrepareBuilder();
        result.hasCanSetOwnMemberAttribute = true;
        result.canSetOwnMemberAttribute_ = value;
        return this;
      }
      public Builder ClearCanSetOwnMemberAttribute() {
        PrepareBuilder();
        result.hasCanSetOwnMemberAttribute = false;
        result.canSetOwnMemberAttribute_ = false;
        return this;
      }
      
      public bool HasCanEnterGame {
        get { return result.hasCanEnterGame; }
      }
      public bool CanEnterGame {
        get { return result.CanEnterGame; }
        set { SetCanEnterGame(value); }
      }
      public Builder SetCanEnterGame(bool value) {
        PrepareBuilder();
        result.hasCanEnterGame = true;
        result.canEnterGame_ = value;
        return this;
      }
      public Builder ClearCanEnterGame() {
        PrepareBuilder();
        result.hasCanEnterGame = false;
        result.canEnterGame_ = false;
        return this;
      }
      
      public bool HasCanSuggest {
        get { return result.hasCanSuggest; }
      }
      public bool CanSuggest {
        get { return result.CanSuggest; }
        set { SetCanSuggest(value); }
      }
      public Builder SetCanSuggest(bool value) {
        PrepareBuilder();
        result.hasCanSuggest = true;
        result.canSuggest_ = value;
        return this;
      }
      public Builder ClearCanSuggest() {
        PrepareBuilder();
        result.hasCanSuggest = false;
        result.canSuggest_ = false;
        return this;
      }
      
      public bool HasCanApprove {
        get { return result.hasCanApprove; }
      }
      public bool CanApprove {
        get { return result.CanApprove; }
        set { SetCanApprove(value); }
      }
      public Builder SetCanApprove(bool value) {
        PrepareBuilder();
        result.hasCanApprove = true;
        result.canApprove_ = value;
        return this;
      }
      public Builder ClearCanApprove() {
        PrepareBuilder();
        result.hasCanApprove = false;
        result.canApprove_ = false;
        return this;
      }
    }
    static ChannelPrivilegeSet() {
      object.ReferenceEquals(global::bgs.protocol.channel.Proto.ChannelRoleSet.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class ChannelRole : pb::GeneratedMessage<ChannelRole, ChannelRole.Builder> {
    private ChannelRole() { }
    private static readonly ChannelRole defaultInstance = new ChannelRole().MakeReadOnly();
    private static readonly string[] _channelRoleFieldNames = new string[] { "id", "privilege", "state" };
    private static readonly uint[] _channelRoleFieldTags = new uint[] { 8, 26, 18 };
    public static ChannelRole DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override ChannelRole DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override ChannelRole ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::bgs.protocol.channel.Proto.ChannelRoleSet.internal__static_bgs_protocol_channel_ChannelRole__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<ChannelRole, ChannelRole.Builder> InternalFieldAccessors {
      get { return global::bgs.protocol.channel.Proto.ChannelRoleSet.internal__static_bgs_protocol_channel_ChannelRole__FieldAccessorTable; }
    }
    
    public const int IdFieldNumber = 1;
    private bool hasId;
    private uint id_;
    public bool HasId {
      get { return hasId; }
    }
    public uint Id {
      get { return id_; }
    }
    
    public const int StateFieldNumber = 2;
    private bool hasState;
    private global::bgs.protocol.RoleState state_;
    public bool HasState {
      get { return hasState; }
    }
    public global::bgs.protocol.RoleState State {
      get { return state_ ?? global::bgs.protocol.RoleState.DefaultInstance; }
    }
    
    public const int PrivilegeFieldNumber = 3;
    private bool hasPrivilege;
    private global::bgs.protocol.channel.ChannelPrivilegeSet privilege_;
    public bool HasPrivilege {
      get { return hasPrivilege; }
    }
    public global::bgs.protocol.channel.ChannelPrivilegeSet Privilege {
      get { return privilege_ ?? global::bgs.protocol.channel.ChannelPrivilegeSet.DefaultInstance; }
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _channelRoleFieldNames;
      if (hasId) {
        output.WriteUInt32(1, field_names[0], Id);
      }
      if (hasState) {
        output.WriteMessage(2, field_names[2], State);
      }
      if (hasPrivilege) {
        output.WriteMessage(3, field_names[1], Privilege);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasId) {
          size += pb::CodedOutputStream.ComputeUInt32Size(1, Id);
        }
        if (hasState) {
          size += pb::CodedOutputStream.ComputeMessageSize(2, State);
        }
        if (hasPrivilege) {
          size += pb::CodedOutputStream.ComputeMessageSize(3, Privilege);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static ChannelRole ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ChannelRole ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ChannelRole ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ChannelRole ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ChannelRole ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ChannelRole ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static ChannelRole ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static ChannelRole ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static ChannelRole ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ChannelRole ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private ChannelRole MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(ChannelRole prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<ChannelRole, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(ChannelRole cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private ChannelRole result;
      
      private ChannelRole PrepareBuilder() {
        if (resultIsReadOnly) {
          ChannelRole original = result;
          result = new ChannelRole();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override ChannelRole MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::bgs.protocol.channel.ChannelRole.Descriptor; }
      }
      
      public override ChannelRole DefaultInstanceForType {
        get { return global::bgs.protocol.channel.ChannelRole.DefaultInstance; }
      }
      
      public override ChannelRole BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is ChannelRole) {
          return MergeFrom((ChannelRole) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(ChannelRole other) {
        if (other == global::bgs.protocol.channel.ChannelRole.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasId) {
          Id = other.Id;
        }
        if (other.HasState) {
          MergeState(other.State);
        }
        if (other.HasPrivilege) {
          MergePrivilege(other.Privilege);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_channelRoleFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _channelRoleFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              result.hasId = input.ReadUInt32(ref result.id_);
              break;
            }
            case 18: {
              global::bgs.protocol.RoleState.Builder subBuilder = global::bgs.protocol.RoleState.CreateBuilder();
              if (result.hasState) {
                subBuilder.MergeFrom(State);
              }
              input.ReadMessage(subBuilder, extensionRegistry);
              State = subBuilder.BuildPartial();
              break;
            }
            case 26: {
              global::bgs.protocol.channel.ChannelPrivilegeSet.Builder subBuilder = global::bgs.protocol.channel.ChannelPrivilegeSet.CreateBuilder();
              if (result.hasPrivilege) {
                subBuilder.MergeFrom(Privilege);
              }
              input.ReadMessage(subBuilder, extensionRegistry);
              Privilege = subBuilder.BuildPartial();
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasId {
        get { return result.hasId; }
      }
      public uint Id {
        get { return result.Id; }
        set { SetId(value); }
      }
      public Builder SetId(uint value) {
        PrepareBuilder();
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder ClearId() {
        PrepareBuilder();
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      public bool HasState {
       get { return result.hasState; }
      }
      public global::bgs.protocol.RoleState State {
        get { return result.State; }
        set { SetState(value); }
      }
      public Builder SetState(global::bgs.protocol.RoleState value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasState = true;
        result.state_ = value;
        return this;
      }
      public Builder SetState(global::bgs.protocol.RoleState.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.hasState = true;
        result.state_ = builderForValue.Build();
        return this;
      }
      public Builder MergeState(global::bgs.protocol.RoleState value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        if (result.hasState &&
            result.state_ != global::bgs.protocol.RoleState.DefaultInstance) {
            result.state_ = global::bgs.protocol.RoleState.CreateBuilder(result.state_).MergeFrom(value).BuildPartial();
        } else {
          result.state_ = value;
        }
        result.hasState = true;
        return this;
      }
      public Builder ClearState() {
        PrepareBuilder();
        result.hasState = false;
        result.state_ = null;
        return this;
      }
      
      public bool HasPrivilege {
       get { return result.hasPrivilege; }
      }
      public global::bgs.protocol.channel.ChannelPrivilegeSet Privilege {
        get { return result.Privilege; }
        set { SetPrivilege(value); }
      }
      public Builder SetPrivilege(global::bgs.protocol.channel.ChannelPrivilegeSet value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasPrivilege = true;
        result.privilege_ = value;
        return this;
      }
      public Builder SetPrivilege(global::bgs.protocol.channel.ChannelPrivilegeSet.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.hasPrivilege = true;
        result.privilege_ = builderForValue.Build();
        return this;
      }
      public Builder MergePrivilege(global::bgs.protocol.channel.ChannelPrivilegeSet value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        if (result.hasPrivilege &&
            result.privilege_ != global::bgs.protocol.channel.ChannelPrivilegeSet.DefaultInstance) {
            result.privilege_ = global::bgs.protocol.channel.ChannelPrivilegeSet.CreateBuilder(result.privilege_).MergeFrom(value).BuildPartial();
        } else {
          result.privilege_ = value;
        }
        result.hasPrivilege = true;
        return this;
      }
      public Builder ClearPrivilege() {
        PrepareBuilder();
        result.hasPrivilege = false;
        result.privilege_ = null;
        return this;
      }
    }
    static ChannelRole() {
      object.ReferenceEquals(global::bgs.protocol.channel.Proto.ChannelRoleSet.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class ChannelRoleSet : pb::GeneratedMessage<ChannelRoleSet, ChannelRoleSet.Builder> {
    private ChannelRoleSet() { }
    private static readonly ChannelRoleSet defaultInstance = new ChannelRoleSet().MakeReadOnly();
    private static readonly string[] _channelRoleSetFieldNames = new string[] { "default_role", "name", "role" };
    private static readonly uint[] _channelRoleSetFieldTags = new uint[] { 18, 26, 10 };
    public static ChannelRoleSet DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override ChannelRoleSet DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override ChannelRoleSet ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::bgs.protocol.channel.Proto.ChannelRoleSet.internal__static_bgs_protocol_channel_ChannelRoleSet__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<ChannelRoleSet, ChannelRoleSet.Builder> InternalFieldAccessors {
      get { return global::bgs.protocol.channel.Proto.ChannelRoleSet.internal__static_bgs_protocol_channel_ChannelRoleSet__FieldAccessorTable; }
    }
    
    public const int RoleFieldNumber = 1;
    private pbc::PopsicleList<global::bgs.protocol.channel.ChannelRole> role_ = new pbc::PopsicleList<global::bgs.protocol.channel.ChannelRole>();
    public scg::IList<global::bgs.protocol.channel.ChannelRole> RoleList {
      get { return role_; }
    }
    public int RoleCount {
      get { return role_.Count; }
    }
    public global::bgs.protocol.channel.ChannelRole GetRole(int index) {
      return role_[index];
    }
    
    public const int DefaultRoleFieldNumber = 2;
    private int defaultRoleMemoizedSerializedSize;
    private pbc::PopsicleList<uint> defaultRole_ = new pbc::PopsicleList<uint>();
    public scg::IList<uint> DefaultRoleList {
      get { return pbc::Lists.AsReadOnly(defaultRole_); }
    }
    public int DefaultRoleCount {
      get { return defaultRole_.Count; }
    }
    public uint GetDefaultRole(int index) {
      return defaultRole_[index];
    }
    
    public const int NameFieldNumber = 3;
    private bool hasName;
    private string name_ = "";
    public bool HasName {
      get { return hasName; }
    }
    public string Name {
      get { return name_; }
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _channelRoleSetFieldNames;
      if (role_.Count > 0) {
        output.WriteMessageArray(1, field_names[2], role_);
      }
      if (defaultRole_.Count > 0) {
        output.WritePackedUInt32Array(2, field_names[0], defaultRoleMemoizedSerializedSize, defaultRole_);
      }
      if (hasName) {
        output.WriteString(3, field_names[1], Name);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        foreach (global::bgs.protocol.channel.ChannelRole element in RoleList) {
          size += pb::CodedOutputStream.ComputeMessageSize(1, element);
        }
        {
          int dataSize = 0;
          foreach (uint element in DefaultRoleList) {
            dataSize += pb::CodedOutputStream.ComputeUInt32SizeNoTag(element);
          }
          size += dataSize;
          if (defaultRole_.Count != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32SizeNoTag(dataSize);
          }
          defaultRoleMemoizedSerializedSize = dataSize;
        }
        if (hasName) {
          size += pb::CodedOutputStream.ComputeStringSize(3, Name);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static ChannelRoleSet ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ChannelRoleSet ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ChannelRoleSet ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ChannelRoleSet ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ChannelRoleSet ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ChannelRoleSet ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static ChannelRoleSet ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static ChannelRoleSet ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static ChannelRoleSet ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ChannelRoleSet ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private ChannelRoleSet MakeReadOnly() {
      role_.MakeReadOnly();
      defaultRole_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(ChannelRoleSet prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<ChannelRoleSet, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(ChannelRoleSet cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private ChannelRoleSet result;
      
      private ChannelRoleSet PrepareBuilder() {
        if (resultIsReadOnly) {
          ChannelRoleSet original = result;
          result = new ChannelRoleSet();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override ChannelRoleSet MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::bgs.protocol.channel.ChannelRoleSet.Descriptor; }
      }
      
      public override ChannelRoleSet DefaultInstanceForType {
        get { return global::bgs.protocol.channel.ChannelRoleSet.DefaultInstance; }
      }
      
      public override ChannelRoleSet BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is ChannelRoleSet) {
          return MergeFrom((ChannelRoleSet) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(ChannelRoleSet other) {
        if (other == global::bgs.protocol.channel.ChannelRoleSet.DefaultInstance) return this;
        PrepareBuilder();
        if (other.role_.Count != 0) {
          result.role_.Add(other.role_);
        }
        if (other.defaultRole_.Count != 0) {
          result.defaultRole_.Add(other.defaultRole_);
        }
        if (other.HasName) {
          Name = other.Name;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_channelRoleSetFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _channelRoleSetFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              input.ReadMessageArray(tag, field_name, result.role_, global::bgs.protocol.channel.ChannelRole.DefaultInstance, extensionRegistry);
              break;
            }
            case 18:
            case 16: {
              input.ReadUInt32Array(tag, field_name, result.defaultRole_);
              break;
            }
            case 26: {
              result.hasName = input.ReadString(ref result.name_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public pbc::IPopsicleList<global::bgs.protocol.channel.ChannelRole> RoleList {
        get { return PrepareBuilder().role_; }
      }
      public int RoleCount {
        get { return result.RoleCount; }
      }
      public global::bgs.protocol.channel.ChannelRole GetRole(int index) {
        return result.GetRole(index);
      }
      public Builder SetRole(int index, global::bgs.protocol.channel.ChannelRole value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.role_[index] = value;
        return this;
      }
      public Builder SetRole(int index, global::bgs.protocol.channel.ChannelRole.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.role_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddRole(global::bgs.protocol.channel.ChannelRole value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.role_.Add(value);
        return this;
      }
      public Builder AddRole(global::bgs.protocol.channel.ChannelRole.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.role_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeRole(scg::IEnumerable<global::bgs.protocol.channel.ChannelRole> values) {
        PrepareBuilder();
        result.role_.Add(values);
        return this;
      }
      public Builder ClearRole() {
        PrepareBuilder();
        result.role_.Clear();
        return this;
      }
      
      public pbc::IPopsicleList<uint> DefaultRoleList {
        get { return PrepareBuilder().defaultRole_; }
      }
      public int DefaultRoleCount {
        get { return result.DefaultRoleCount; }
      }
      public uint GetDefaultRole(int index) {
        return result.GetDefaultRole(index);
      }
      public Builder SetDefaultRole(int index, uint value) {
        PrepareBuilder();
        result.defaultRole_[index] = value;
        return this;
      }
      public Builder AddDefaultRole(uint value) {
        PrepareBuilder();
        result.defaultRole_.Add(value);
        return this;
      }
      public Builder AddRangeDefaultRole(scg::IEnumerable<uint> values) {
        PrepareBuilder();
        result.defaultRole_.Add(values);
        return this;
      }
      public Builder ClearDefaultRole() {
        PrepareBuilder();
        result.defaultRole_.Clear();
        return this;
      }
      
      public bool HasName {
        get { return result.hasName; }
      }
      public string Name {
        get { return result.Name; }
        set { SetName(value); }
      }
      public Builder SetName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder ClearName() {
        PrepareBuilder();
        result.hasName = false;
        result.name_ = "";
        return this;
      }
    }
    static ChannelRoleSet() {
      object.ReferenceEquals(global::bgs.protocol.channel.Proto.ChannelRoleSet.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
