; ==========
; Configuration File Template
; ==========
; This is a template configuration file which can be modified as desired. The following branches are available for your convenience: 
; - Community branch (recommended): https://github.com/blizzless/blizzless-diiis/tree/community
; - Test-stable branch: https://github.com/blizzless/blizzless-diiis/
; - Master branch: https://github.com/blizzless/blizzless-diiis/tree/master

; Battle Server Settings 
; Settings for Bnet
[Battle-Server]
Enabled = true
BindIP = 127.0.0.1
WebPort = 9800
Port = 1119
BindIPv6 = ::1
MOTD = Welcome to Diablo 3! {act} - {quest}

[IWServer]
IWServer = false

; Settings for REST
[REST]
IP = 127.0.0.1
Public = true
PublicIP = 127.0.0.1
PORT = 8888
WebUrl = http://127.0.0.1:8888

[NAT]
Enabled = false
PublicIP = 127.0.0.1

; Command settings
[Command]
CommandPrefix = !

; Settings for game
[Game-Server]
Enabled = true
CoreActive = true
BindIP = 127.0.0.1
WebPort = 9100
Port = 2001
BindIPv6 = ::1
DRLGemu = true
IsLocalDev = true

; ==========
; Game Modding Configuration
; For documentation, please check https://github.com/blizzless/blizzless-diiis/blob/community/docs/game-world-settings.md
; Multipliers for various gameplay rates
RateExp = 1
RateMoney = 2
RateDrop = 1
RateChangeDrop = 1
RateMonsterHP = 1.2
RateMonsterDMG = 1.2


MonsterThinkTick = 0.5

; Quality and identification chances for items
ChanceHighQualityUnidentified = 30
ChanceNormalUnidentified = 5

; Boss health and damage multipliers
BossHealthMultiplier = 3
BossDamageMultiplier = 3

; Nephalem Rift progress multiplier
NephalemRiftProgressMultiplier = 4

; Health potion mechanics
HealthPotionConsumable = false
HealthPotionRestorePercentage = 60
HealthPotionCooldown = 5
ResurrectionCharges = 5

; Player attribute modifiers
StrengthMultiplier = 2
StrengthParagonMultiplier = 2
DexterityMultiplier = 1
DexterityParagonMultiplier = 1
IntelligenceMultiplier = 1
IntelligenceParagonMultiplier = 1
VitalityMultiplier = 1
VitalityParagonMultiplier = 1

; Minimap visibility settings
ForceMinimapVisibility = true

; Option to bypass bugged quests - only for smoother in-game phase transitions
; Do not use if your intent is to fix quests, only to bypass them
BypassBuggedQuests = true

; Quest saving behavior
AutoSaveQuests = true

; Waypoint settings
UnlockAllWaypoints = true

; activates more arrows in quests for debugging purposes, and faster phase transitions
DebugMoreArrowsInQuests = true

; Broadcasts a message saying when a player advances a quests, with info
; about the act, quest name, and step number
; Current format looks as following: "Act I (0) - The Fallen Star (12345) Step 2"
LogQuestAdvance = true
LogQuestAdvanceFormat = {act} - {quest} Step {step}

[Balance]
BalanceEnabled = true

; Skeleton king (Leoric) adjustments for damage and health
SkeletonKingDamageMultiplier = 0.35
SkeletonKingHealthMultiplier = 0.35
SkeletonKingWalkSpeed = 0.360

; Maghda adjustments for damage and health
MaghdaHealthMultiplier = 30
MaghdaDamageMultiplier = 5
MaghdaWalkSpeed = 0.360

; Normal boss adjustments for damage and health
NormalBossDamageMultiplier = 0.9
NormalBossHealthMultiplier = 0.9
NormalBossWalkSpeed = 0.360

; # Player Balance
; necro
FixedCooldownSeconds=-1
NecroArmyOfTheDeadDamageMultiplier=-1
; ===================
; Log Output Settings
; AnsiLog for visualization, ConsoleLog for debugging, and PacketLog for packet analysis

[AnsiLog]
Enabled = false
Target = Ansi
IncludeTimeStamps = true
MinimumLevel = MethodTrace
MaximumLevel = Fatal

[ConsoleLog]
Enabled = true
Target = Console
IncludeTimeStamps = true
MinimumLevel = MethodTrace
MaximumLevel = Fatal

[PacketLog]
Enabled = true
Target = file
FileName = packet.log
IncludeTimeStamps = true
MinimumLevel = Debug
MaximumLevel = PacketDump