// Generated by ProtoGen, Version=2.4.1.473, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace bgs.protocol.diag.v1 {
  
  namespace Proto {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public static partial class DiagService {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_bgs_protocol_diag_v1_GetVarRequest__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.diag.v1.GetVarRequest, global::bgs.protocol.diag.v1.GetVarRequest.Builder> internal__static_bgs_protocol_diag_v1_GetVarRequest__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_bgs_protocol_diag_v1_GetVarResponse__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.diag.v1.GetVarResponse, global::bgs.protocol.diag.v1.GetVarResponse.Builder> internal__static_bgs_protocol_diag_v1_GetVarResponse__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_bgs_protocol_diag_v1_SetVarRequest__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.diag.v1.SetVarRequest, global::bgs.protocol.diag.v1.SetVarRequest.Builder> internal__static_bgs_protocol_diag_v1_SetVarRequest__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_bgs_protocol_diag_v1_QueryRequest__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.diag.v1.QueryRequest, global::bgs.protocol.diag.v1.QueryRequest.Builder> internal__static_bgs_protocol_diag_v1_QueryRequest__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_bgs_protocol_diag_v1_Row__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.diag.v1.Row, global::bgs.protocol.diag.v1.Row.Builder> internal__static_bgs_protocol_diag_v1_Row__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_bgs_protocol_diag_v1_QueryResponse__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.diag.v1.QueryResponse, global::bgs.protocol.diag.v1.QueryResponse.Builder> internal__static_bgs_protocol_diag_v1_QueryResponse__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;
      
      static DiagService() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            "CiRiZ3MvbG93L3BiL2NsaWVudC9kaWFnX3NlcnZpY2UucHJvdG8SFGJncy5w" + 
            "cm90b2NvbC5kaWFnLnYxGiFiZ3MvbG93L3BiL2NsaWVudC9ycGNfdHlwZXMu" + 
            "cHJvdG8iIwoNR2V0VmFyUmVxdWVzdBISCgRuYW1lGAEgAigJUgRuYW1lIiYK" + 
            "DkdldFZhclJlc3BvbnNlEhQKBXZhbHVlGAEgAigJUgV2YWx1ZSI5Cg1TZXRW" + 
            "YXJSZXF1ZXN0EhIKBG5hbWUYASACKAlSBG5hbWUSFAoFdmFsdWUYAiACKAlS" + 
            "BXZhbHVlIjYKDFF1ZXJ5UmVxdWVzdBISCgRuYW1lGAEgAigJUgRuYW1lEhIK" + 
            "BGFyZ3MYAiADKAlSBGFyZ3MiHQoDUm93EhYKBnZhbHVlcxgBIAMoCVIGdmFs" + 
            "dWVzImwKDVF1ZXJ5UmVzcG9uc2USEgoEbmFtZRgBIAIoCVIEbmFtZRIYCgdj" + 
            "b2x1bW5zGAIgAygJUgdjb2x1bW5zEi0KBHJvd3MYAyADKAsyGS5iZ3MucHJv" + 
            "dG9jb2wuZGlhZy52MS5Sb3dSBHJvd3MyvQIKC0RpYWdTZXJ2aWNlElsKBkdl" + 
            "dFZhchIjLmJncy5wcm90b2NvbC5kaWFnLnYxLkdldFZhclJlcXVlc3QaJC5i" + 
            "Z3MucHJvdG9jb2wuZGlhZy52MS5HZXRWYXJSZXNwb25zZSIGgvkrAggBEksK" + 
            "BlNldFZhchIjLmJncy5wcm90b2NvbC5kaWFnLnYxLlNldFZhclJlcXVlc3Qa" + 
            "FC5iZ3MucHJvdG9jb2wuTm9EYXRhIgaC+SsCCAISWAoFUXVlcnkSIi5iZ3Mu" + 
            "cHJvdG9jb2wuZGlhZy52MS5RdWVyeVJlcXVlc3QaIy5iZ3MucHJvdG9jb2wu" + 
            "ZGlhZy52MS5RdWVyeVJlc3BvbnNlIgaC+SsCCAMaKoL5KyAKHmJuZXQucHJv" + 
            "dG9jb2wuZGlhZy5EaWFnU2VydmljZYr5KwIIAUIxChVibmV0LnByb3RvY29s" + 
            "LmRpYWcudjFCEERpYWdTZXJ2aWNlUHJvdG9IAoABAIgBAQ==");
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_bgs_protocol_diag_v1_GetVarRequest__Descriptor = Descriptor.MessageTypes[0];
          internal__static_bgs_protocol_diag_v1_GetVarRequest__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.diag.v1.GetVarRequest, global::bgs.protocol.diag.v1.GetVarRequest.Builder>(internal__static_bgs_protocol_diag_v1_GetVarRequest__Descriptor,
                  new string[] { "Name", });
          internal__static_bgs_protocol_diag_v1_GetVarResponse__Descriptor = Descriptor.MessageTypes[1];
          internal__static_bgs_protocol_diag_v1_GetVarResponse__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.diag.v1.GetVarResponse, global::bgs.protocol.diag.v1.GetVarResponse.Builder>(internal__static_bgs_protocol_diag_v1_GetVarResponse__Descriptor,
                  new string[] { "Value", });
          internal__static_bgs_protocol_diag_v1_SetVarRequest__Descriptor = Descriptor.MessageTypes[2];
          internal__static_bgs_protocol_diag_v1_SetVarRequest__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.diag.v1.SetVarRequest, global::bgs.protocol.diag.v1.SetVarRequest.Builder>(internal__static_bgs_protocol_diag_v1_SetVarRequest__Descriptor,
                  new string[] { "Name", "Value", });
          internal__static_bgs_protocol_diag_v1_QueryRequest__Descriptor = Descriptor.MessageTypes[3];
          internal__static_bgs_protocol_diag_v1_QueryRequest__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.diag.v1.QueryRequest, global::bgs.protocol.diag.v1.QueryRequest.Builder>(internal__static_bgs_protocol_diag_v1_QueryRequest__Descriptor,
                  new string[] { "Name", "Args", });
          internal__static_bgs_protocol_diag_v1_Row__Descriptor = Descriptor.MessageTypes[4];
          internal__static_bgs_protocol_diag_v1_Row__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.diag.v1.Row, global::bgs.protocol.diag.v1.Row.Builder>(internal__static_bgs_protocol_diag_v1_Row__Descriptor,
                  new string[] { "Values", });
          internal__static_bgs_protocol_diag_v1_QueryResponse__Descriptor = Descriptor.MessageTypes[5];
          internal__static_bgs_protocol_diag_v1_QueryResponse__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::bgs.protocol.diag.v1.QueryResponse, global::bgs.protocol.diag.v1.QueryResponse.Builder>(internal__static_bgs_protocol_diag_v1_QueryResponse__Descriptor,
                  new string[] { "Name", "Columns", "Rows", });
          pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
          RegisterAllExtensions(registry);
          global::bgs.protocol.RpcTypes.RegisterAllExtensions(registry);
          return registry;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            global::bgs.protocol.RpcTypes.Descriptor, 
            }, assigner);
      }
      #endregion
      
    }
  }
  #region Messages
  
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class GetVarRequest : pb::GeneratedMessage<GetVarRequest, GetVarRequest.Builder> {
    private GetVarRequest() { }
    private static readonly GetVarRequest defaultInstance = new GetVarRequest().MakeReadOnly();
    public static GetVarRequest DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override GetVarRequest DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override GetVarRequest ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::bgs.protocol.diag.v1.Proto.DiagService.internal__static_bgs_protocol_diag_v1_GetVarRequest__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<GetVarRequest, GetVarRequest.Builder> InternalFieldAccessors {
      get { return global::bgs.protocol.diag.v1.Proto.DiagService.internal__static_bgs_protocol_diag_v1_GetVarRequest__FieldAccessorTable; }
    }
    
    public const int NameFieldNumber = 1;
    private bool hasName;
    private string name_ = "";
    public bool HasName {
      get { return hasName; }
    }
    public string Name {
      get { return name_; }
    }
    
    public static GetVarRequest ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static GetVarRequest ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static GetVarRequest ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static GetVarRequest ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static GetVarRequest ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static GetVarRequest ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static GetVarRequest ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static GetVarRequest ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static GetVarRequest ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static GetVarRequest ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private GetVarRequest MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(GetVarRequest prototype) {
      return new Builder(prototype);
    }
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<GetVarRequest, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(GetVarRequest cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private GetVarRequest result;
      
      private GetVarRequest PrepareBuilder() {
        if (resultIsReadOnly) {
          GetVarRequest original = result;
          result = new GetVarRequest();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override GetVarRequest MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::bgs.protocol.diag.v1.GetVarRequest.Descriptor; }
      }
      
      public override GetVarRequest DefaultInstanceForType {
        get { return global::bgs.protocol.diag.v1.GetVarRequest.DefaultInstance; }
      }
      
      public override GetVarRequest BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      
      public bool HasName {
        get { return result.hasName; }
      }
      public string Name {
        get { return result.Name; }
        set { SetName(value); }
      }
      public Builder SetName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder ClearName() {
        PrepareBuilder();
        result.hasName = false;
        result.name_ = "";
        return this;
      }
    }
    static GetVarRequest() {
      object.ReferenceEquals(global::bgs.protocol.diag.v1.Proto.DiagService.Descriptor, null);
    }
  }
  
  
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class GetVarResponse : pb::GeneratedMessage<GetVarResponse, GetVarResponse.Builder> {
    private GetVarResponse() { }
    private static readonly GetVarResponse defaultInstance = new GetVarResponse().MakeReadOnly();
    public static GetVarResponse DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override GetVarResponse DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override GetVarResponse ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::bgs.protocol.diag.v1.Proto.DiagService.internal__static_bgs_protocol_diag_v1_GetVarResponse__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<GetVarResponse, GetVarResponse.Builder> InternalFieldAccessors {
      get { return global::bgs.protocol.diag.v1.Proto.DiagService.internal__static_bgs_protocol_diag_v1_GetVarResponse__FieldAccessorTable; }
    }
    
    public const int ValueFieldNumber = 1;
    private bool hasValue;
    private string value_ = "";
    public bool HasValue {
      get { return hasValue; }
    }
    public string Value {
      get { return value_; }
    }
    
    public static GetVarResponse ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static GetVarResponse ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static GetVarResponse ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static GetVarResponse ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static GetVarResponse ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static GetVarResponse ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static GetVarResponse ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static GetVarResponse ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static GetVarResponse ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static GetVarResponse ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private GetVarResponse MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(GetVarResponse prototype) {
      return new Builder(prototype);
    }
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<GetVarResponse, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(GetVarResponse cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private GetVarResponse result;
      
      private GetVarResponse PrepareBuilder() {
        if (resultIsReadOnly) {
          GetVarResponse original = result;
          result = new GetVarResponse();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override GetVarResponse MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::bgs.protocol.diag.v1.GetVarResponse.Descriptor; }
      }
      
      public override GetVarResponse DefaultInstanceForType {
        get { return global::bgs.protocol.diag.v1.GetVarResponse.DefaultInstance; }
      }
      
      public override GetVarResponse BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      
      public bool HasValue {
        get { return result.hasValue; }
      }
      public string Value {
        get { return result.Value; }
        set { SetValue(value); }
      }
      public Builder SetValue(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder ClearValue() {
        PrepareBuilder();
        result.hasValue = false;
        result.value_ = "";
        return this;
      }
    }
    static GetVarResponse() {
      object.ReferenceEquals(global::bgs.protocol.diag.v1.Proto.DiagService.Descriptor, null);
    }
  }
  
  
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class SetVarRequest : pb::GeneratedMessage<SetVarRequest, SetVarRequest.Builder> {
    private SetVarRequest() { }
    private static readonly SetVarRequest defaultInstance = new SetVarRequest().MakeReadOnly();
    public static SetVarRequest DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override SetVarRequest DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override SetVarRequest ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::bgs.protocol.diag.v1.Proto.DiagService.internal__static_bgs_protocol_diag_v1_SetVarRequest__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<SetVarRequest, SetVarRequest.Builder> InternalFieldAccessors {
      get { return global::bgs.protocol.diag.v1.Proto.DiagService.internal__static_bgs_protocol_diag_v1_SetVarRequest__FieldAccessorTable; }
    }
    
    public const int NameFieldNumber = 1;
    private bool hasName;
    private string name_ = "";
    public bool HasName {
      get { return hasName; }
    }
    public string Name {
      get { return name_; }
    }
    
    public const int ValueFieldNumber = 2;
    private bool hasValue;
    private string value_ = "";
    public bool HasValue {
      get { return hasValue; }
    }
    public string Value {
      get { return value_; }
    }
    
    public static SetVarRequest ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static SetVarRequest ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static SetVarRequest ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static SetVarRequest ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static SetVarRequest ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static SetVarRequest ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static SetVarRequest ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static SetVarRequest ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static SetVarRequest ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static SetVarRequest ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private SetVarRequest MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(SetVarRequest prototype) {
      return new Builder(prototype);
    }
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<SetVarRequest, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(SetVarRequest cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private SetVarRequest result;
      
      private SetVarRequest PrepareBuilder() {
        if (resultIsReadOnly) {
          SetVarRequest original = result;
          result = new SetVarRequest();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override SetVarRequest MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::bgs.protocol.diag.v1.SetVarRequest.Descriptor; }
      }
      
      public override SetVarRequest DefaultInstanceForType {
        get { return global::bgs.protocol.diag.v1.SetVarRequest.DefaultInstance; }
      }
      
      public override SetVarRequest BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      
      public bool HasName {
        get { return result.hasName; }
      }
      public string Name {
        get { return result.Name; }
        set { SetName(value); }
      }
      public Builder SetName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder ClearName() {
        PrepareBuilder();
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      public bool HasValue {
        get { return result.hasValue; }
      }
      public string Value {
        get { return result.Value; }
        set { SetValue(value); }
      }
      public Builder SetValue(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder ClearValue() {
        PrepareBuilder();
        result.hasValue = false;
        result.value_ = "";
        return this;
      }
    }
    static SetVarRequest() {
      object.ReferenceEquals(global::bgs.protocol.diag.v1.Proto.DiagService.Descriptor, null);
    }
  }
  
  
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class QueryRequest : pb::GeneratedMessage<QueryRequest, QueryRequest.Builder> {
    private QueryRequest() { }
    private static readonly QueryRequest defaultInstance = new QueryRequest().MakeReadOnly();
    public static QueryRequest DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override QueryRequest DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override QueryRequest ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::bgs.protocol.diag.v1.Proto.DiagService.internal__static_bgs_protocol_diag_v1_QueryRequest__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<QueryRequest, QueryRequest.Builder> InternalFieldAccessors {
      get { return global::bgs.protocol.diag.v1.Proto.DiagService.internal__static_bgs_protocol_diag_v1_QueryRequest__FieldAccessorTable; }
    }
    
    public const int NameFieldNumber = 1;
    private bool hasName;
    private string name_ = "";
    public bool HasName {
      get { return hasName; }
    }
    public string Name {
      get { return name_; }
    }
    
    public const int ArgsFieldNumber = 2;
    private pbc::PopsicleList<string> args_ = new pbc::PopsicleList<string>();
    public scg::IList<string> ArgsList {
      get { return pbc::Lists.AsReadOnly(args_); }
    }
    public int ArgsCount {
      get { return args_.Count; }
    }
    public string GetArgs(int index) {
      return args_[index];
    }
    
    public static QueryRequest ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static QueryRequest ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static QueryRequest ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static QueryRequest ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static QueryRequest ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static QueryRequest ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static QueryRequest ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static QueryRequest ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static QueryRequest ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static QueryRequest ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private QueryRequest MakeReadOnly() {
      args_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(QueryRequest prototype) {
      return new Builder(prototype);
    }
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<QueryRequest, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(QueryRequest cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private QueryRequest result;
      
      private QueryRequest PrepareBuilder() {
        if (resultIsReadOnly) {
          QueryRequest original = result;
          result = new QueryRequest();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override QueryRequest MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::bgs.protocol.diag.v1.QueryRequest.Descriptor; }
      }
      
      public override QueryRequest DefaultInstanceForType {
        get { return global::bgs.protocol.diag.v1.QueryRequest.DefaultInstance; }
      }
      
      public override QueryRequest BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      
      public bool HasName {
        get { return result.hasName; }
      }
      public string Name {
        get { return result.Name; }
        set { SetName(value); }
      }
      public Builder SetName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder ClearName() {
        PrepareBuilder();
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      public pbc::IPopsicleList<string> ArgsList {
        get { return PrepareBuilder().args_; }
      }
      public int ArgsCount {
        get { return result.ArgsCount; }
      }
      public string GetArgs(int index) {
        return result.GetArgs(index);
      }
      public Builder SetArgs(int index, string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.args_[index] = value;
        return this;
      }
      public Builder AddArgs(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.args_.Add(value);
        return this;
      }
      public Builder AddRangeArgs(scg::IEnumerable<string> values) {
        PrepareBuilder();
        result.args_.Add(values);
        return this;
      }
      public Builder ClearArgs() {
        PrepareBuilder();
        result.args_.Clear();
        return this;
      }
    }
    static QueryRequest() {
      object.ReferenceEquals(global::bgs.protocol.diag.v1.Proto.DiagService.Descriptor, null);
    }
  }
  
  
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class Row : pb::GeneratedMessage<Row, Row.Builder> {
    private Row() { }
    private static readonly Row defaultInstance = new Row().MakeReadOnly();
    public static Row DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override Row DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override Row ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::bgs.protocol.diag.v1.Proto.DiagService.internal__static_bgs_protocol_diag_v1_Row__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<Row, Row.Builder> InternalFieldAccessors {
      get { return global::bgs.protocol.diag.v1.Proto.DiagService.internal__static_bgs_protocol_diag_v1_Row__FieldAccessorTable; }
    }
    
    public const int ValuesFieldNumber = 1;
    private pbc::PopsicleList<string> values_ = new pbc::PopsicleList<string>();
    public scg::IList<string> ValuesList {
      get { return pbc::Lists.AsReadOnly(values_); }
    }
    public int ValuesCount {
      get { return values_.Count; }
    }
    public string GetValues(int index) {
      return values_[index];
    }
    
    public static Row ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static Row ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static Row ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static Row ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static Row ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static Row ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static Row ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static Row ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static Row ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static Row ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private Row MakeReadOnly() {
      values_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(Row prototype) {
      return new Builder(prototype);
    }
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<Row, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(Row cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private Row result;
      
      private Row PrepareBuilder() {
        if (resultIsReadOnly) {
          Row original = result;
          result = new Row();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override Row MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::bgs.protocol.diag.v1.Row.Descriptor; }
      }
      
      public override Row DefaultInstanceForType {
        get { return global::bgs.protocol.diag.v1.Row.DefaultInstance; }
      }
      
      public override Row BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      
      public pbc::IPopsicleList<string> ValuesList {
        get { return PrepareBuilder().values_; }
      }
      public int ValuesCount {
        get { return result.ValuesCount; }
      }
      public string GetValues(int index) {
        return result.GetValues(index);
      }
      public Builder SetValues(int index, string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.values_[index] = value;
        return this;
      }
      public Builder AddValues(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.values_.Add(value);
        return this;
      }
      public Builder AddRangeValues(scg::IEnumerable<string> values) {
        PrepareBuilder();
        result.values_.Add(values);
        return this;
      }
      public Builder ClearValues() {
        PrepareBuilder();
        result.values_.Clear();
        return this;
      }
    }
    static Row() {
      object.ReferenceEquals(global::bgs.protocol.diag.v1.Proto.DiagService.Descriptor, null);
    }
  }
  
  
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class QueryResponse : pb::GeneratedMessage<QueryResponse, QueryResponse.Builder> {
    private QueryResponse() { }
    private static readonly QueryResponse defaultInstance = new QueryResponse().MakeReadOnly();
    public static QueryResponse DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override QueryResponse DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override QueryResponse ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::bgs.protocol.diag.v1.Proto.DiagService.internal__static_bgs_protocol_diag_v1_QueryResponse__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<QueryResponse, QueryResponse.Builder> InternalFieldAccessors {
      get { return global::bgs.protocol.diag.v1.Proto.DiagService.internal__static_bgs_protocol_diag_v1_QueryResponse__FieldAccessorTable; }
    }
    
    public const int NameFieldNumber = 1;
    private bool hasName;
    private string name_ = "";
    public bool HasName {
      get { return hasName; }
    }
    public string Name {
      get { return name_; }
    }
    
    public const int ColumnsFieldNumber = 2;
    private pbc::PopsicleList<string> columns_ = new pbc::PopsicleList<string>();
    public scg::IList<string> ColumnsList {
      get { return pbc::Lists.AsReadOnly(columns_); }
    }
    public int ColumnsCount {
      get { return columns_.Count; }
    }
    public string GetColumns(int index) {
      return columns_[index];
    }
    
    public const int RowsFieldNumber = 3;
    private pbc::PopsicleList<global::bgs.protocol.diag.v1.Row> rows_ = new pbc::PopsicleList<global::bgs.protocol.diag.v1.Row>();
    public scg::IList<global::bgs.protocol.diag.v1.Row> RowsList {
      get { return rows_; }
    }
    public int RowsCount {
      get { return rows_.Count; }
    }
    public global::bgs.protocol.diag.v1.Row GetRows(int index) {
      return rows_[index];
    }
    
    public static QueryResponse ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static QueryResponse ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static QueryResponse ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static QueryResponse ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static QueryResponse ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static QueryResponse ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static QueryResponse ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static QueryResponse ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static QueryResponse ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static QueryResponse ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private QueryResponse MakeReadOnly() {
      columns_.MakeReadOnly();
      rows_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(QueryResponse prototype) {
      return new Builder(prototype);
    }
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<QueryResponse, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(QueryResponse cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private QueryResponse result;
      
      private QueryResponse PrepareBuilder() {
        if (resultIsReadOnly) {
          QueryResponse original = result;
          result = new QueryResponse();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override QueryResponse MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::bgs.protocol.diag.v1.QueryResponse.Descriptor; }
      }
      
      public override QueryResponse DefaultInstanceForType {
        get { return global::bgs.protocol.diag.v1.QueryResponse.DefaultInstance; }
      }
      
      public override QueryResponse BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      
      public bool HasName {
        get { return result.hasName; }
      }
      public string Name {
        get { return result.Name; }
        set { SetName(value); }
      }
      public Builder SetName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder ClearName() {
        PrepareBuilder();
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      public pbc::IPopsicleList<string> ColumnsList {
        get { return PrepareBuilder().columns_; }
      }
      public int ColumnsCount {
        get { return result.ColumnsCount; }
      }
      public string GetColumns(int index) {
        return result.GetColumns(index);
      }
      public Builder SetColumns(int index, string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.columns_[index] = value;
        return this;
      }
      public Builder AddColumns(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.columns_.Add(value);
        return this;
      }
      public Builder AddRangeColumns(scg::IEnumerable<string> values) {
        PrepareBuilder();
        result.columns_.Add(values);
        return this;
      }
      public Builder ClearColumns() {
        PrepareBuilder();
        result.columns_.Clear();
        return this;
      }
      
      public pbc::IPopsicleList<global::bgs.protocol.diag.v1.Row> RowsList {
        get { return PrepareBuilder().rows_; }
      }
      public int RowsCount {
        get { return result.RowsCount; }
      }
      public global::bgs.protocol.diag.v1.Row GetRows(int index) {
        return result.GetRows(index);
      }
      public Builder SetRows(int index, global::bgs.protocol.diag.v1.Row value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.rows_[index] = value;
        return this;
      }
      public Builder SetRows(int index, global::bgs.protocol.diag.v1.Row.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.rows_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddRows(global::bgs.protocol.diag.v1.Row value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.rows_.Add(value);
        return this;
      }
      public Builder AddRows(global::bgs.protocol.diag.v1.Row.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.rows_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeRows(scg::IEnumerable<global::bgs.protocol.diag.v1.Row> values) {
        PrepareBuilder();
        result.rows_.Add(values);
        return this;
      }
      public Builder ClearRows() {
        PrepareBuilder();
        result.rows_.Clear();
        return this;
      }
    }
    static QueryResponse() {
      object.ReferenceEquals(global::bgs.protocol.diag.v1.Proto.DiagService.Descriptor, null);
    }
  }
  
  #endregion
  
  #region Services
  
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public abstract class DiagService : pb::IService {
    public abstract void GetVar(
        pb::IRpcController controller,
        global::bgs.protocol.diag.v1.GetVarRequest request,
        global::System.Action<global::bgs.protocol.diag.v1.GetVarResponse> done);
    public abstract void SetVar(
        pb::IRpcController controller,
        global::bgs.protocol.diag.v1.SetVarRequest request,
        global::System.Action<global::bgs.protocol.NoData> done);
    public abstract void Query(
        pb::IRpcController controller,
        global::bgs.protocol.diag.v1.QueryRequest request,
        global::System.Action<global::bgs.protocol.diag.v1.QueryResponse> done);
    
    public static pbd::ServiceDescriptor Descriptor {
      get { return Proto.DiagService.Descriptor.Services[0]; }
    }
    public pbd::ServiceDescriptor DescriptorForType {
      get { return Descriptor; }
    }
    
    public void CallMethod(
        pbd::MethodDescriptor method,
        pb::IRpcController controller,
        pb::IMessage request,
        global::System.Action<pb::IMessage> done) {
      if (method.Service != Descriptor) {
        throw new global::System.ArgumentException(
            "Service.CallMethod() given method descriptor for wrong service type.");
      }
      switch(method.Index) {
        case 0:
          this.GetVar(controller, (global::bgs.protocol.diag.v1.GetVarRequest) request,
              pb::RpcUtil.SpecializeCallback<global::bgs.protocol.diag.v1.GetVarResponse>(
              done));
          return;
        case 1:
          this.SetVar(controller, (global::bgs.protocol.diag.v1.SetVarRequest) request,
              pb::RpcUtil.SpecializeCallback<global::bgs.protocol.NoData>(
              done));
          return;
        case 2:
          this.Query(controller, (global::bgs.protocol.diag.v1.QueryRequest) request,
              pb::RpcUtil.SpecializeCallback<global::bgs.protocol.diag.v1.QueryResponse>(
              done));
          return;
        default:
          throw new global::System.InvalidOperationException("Can't get here.");
      }
    }
    
    public pb::IMessage GetRequestPrototype(pbd::MethodDescriptor method) {
      if (method.Service != Descriptor) {
        throw new global::System.ArgumentException(
            "Service.GetRequestPrototype() given method descriptor for wrong service type.");
      }
      switch(method.Index) {
        case 0:
          return global::bgs.protocol.diag.v1.GetVarRequest.DefaultInstance;
        case 1:
          return global::bgs.protocol.diag.v1.SetVarRequest.DefaultInstance;
        case 2:
          return global::bgs.protocol.diag.v1.QueryRequest.DefaultInstance;
        default:
          throw new global::System.InvalidOperationException("Can't get here.");
      }
    }
    
    public pb::IMessage GetResponsePrototype(pbd::MethodDescriptor method) {
      if (method.Service != Descriptor) {
        throw new global::System.ArgumentException(
            "Service.GetResponsePrototype() given method descriptor for wrong service type.");
      }
      switch(method.Index) {
        case 0:
          return global::bgs.protocol.diag.v1.GetVarResponse.DefaultInstance;
        case 1:
          return global::bgs.protocol.NoData.DefaultInstance;
        case 2:
          return global::bgs.protocol.diag.v1.QueryResponse.DefaultInstance;
        default:
          throw new global::System.InvalidOperationException("Can't get here.");
      }
    }
    
    public static Stub CreateStub(pb::IRpcChannel channel) {
      return new Stub(channel);
    }
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public class Stub : global::bgs.protocol.diag.v1.DiagService {
      internal Stub(pb::IRpcChannel channel) {
        this.channel = channel;
      }
      
      private readonly pb::IRpcChannel channel;
      
      public pb::IRpcChannel Channel {
        get { return channel; }
      }
      
      public override void GetVar(
          pb::IRpcController controller,
          global::bgs.protocol.diag.v1.GetVarRequest request,
          global::System.Action<global::bgs.protocol.diag.v1.GetVarResponse> done) {
        channel.CallMethod(Descriptor.Methods[0],
            controller, request, global::bgs.protocol.diag.v1.GetVarResponse.DefaultInstance,
            pb::RpcUtil.GeneralizeCallback<global::bgs.protocol.diag.v1.GetVarResponse, global::bgs.protocol.diag.v1.GetVarResponse.Builder>(done, global::bgs.protocol.diag.v1.GetVarResponse.DefaultInstance));
      }
      
      public override void SetVar(
          pb::IRpcController controller,
          global::bgs.protocol.diag.v1.SetVarRequest request,
          global::System.Action<global::bgs.protocol.NoData> done) {
        channel.CallMethod(Descriptor.Methods[1],
            controller, request, global::bgs.protocol.NoData.DefaultInstance,
            pb::RpcUtil.GeneralizeCallback<global::bgs.protocol.NoData, global::bgs.protocol.NoData.Builder>(done, global::bgs.protocol.NoData.DefaultInstance));
      }
      
      public override void Query(
          pb::IRpcController controller,
          global::bgs.protocol.diag.v1.QueryRequest request,
          global::System.Action<global::bgs.protocol.diag.v1.QueryResponse> done) {
        channel.CallMethod(Descriptor.Methods[2],
            controller, request, global::bgs.protocol.diag.v1.QueryResponse.DefaultInstance,
            pb::RpcUtil.GeneralizeCallback<global::bgs.protocol.diag.v1.QueryResponse, global::bgs.protocol.diag.v1.QueryResponse.Builder>(done, global::bgs.protocol.diag.v1.QueryResponse.DefaultInstance));
      }
    }
  }
  #endregion
  
}

#endregion Designer generated code
